name: Deploy GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'README.md'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install pandoc
      run: sudo apt-get install -y pandoc
      
    - name: Convert README.md to HTML
      run: |
        mkdir -p public
        pandoc README.md -f markdown -t html -s -o public/index.html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
